### ISSUE TITLE
crawl pageid result is break_times

### ISSUE THREAD

**Issue by mongoole** [TLYu0419/facebook_crawler#10]
import io,sys
import facebook_crawler

sys.stdout = io.TextIOWrapper(sys.stdout.buffer,encoding='utf8') #改变标准输出的默认编码

pageurl= 'https://www.facebook.com/diudiu333'
facebook_crawler.Crawl_PagePosts(pageurl=pageurl, until_date='2021-11-22')

break_times: 1
break_times: 2
break_times: 3
break_times: 4
break_times: 5
break_times: 6

**Comment by TLYu0419** [comment]
@mongoole
I've solved this problem. Please install the latest version(0.0.25).

**Comment by lshowo** [comment]
> @mongoole
> I've solved this problem. Please install the latest version(0.0.25).

sorry, the result is still break_times😭

**Comment by TLYu0419** [comment]
@lshowo 
I can crawl Fanspages' posts correctly. Could you provide your target fanspage link?
(https://github.com/TLYu0419/facebook_crawler/blob/main/sample/FansPages.ipynb)
