### ISSUE TITLE
項目現在還可以使用嗎？

### ISSUE THREAD

**Issue by bestRunner** [TLYu0419/facebook_crawler#14]
出現解析失敗的情況，PageID提取不到，且拉數據的接口（https://www.facebook.com/pages_reaction_units/more/）也不通了

**Comment by TLYu0419** [comment]
It still works well. Maybe you can try to change your computer IP, and then it will be fine.

**Comment by bestRunner** [comment]
> It still works well. Maybe you can try to change your computer IP, and then it will be fine.

我使用的是香港的IP，還是不行尼，換了幾個，請問您那邊工作的IP是哪裏的？

**Comment by TLYu0419** [comment]
@bestRunner 
Taiwan. By the way, could you please provide the page that you want to crawl? Thank!

**Comment by bestRunner** [comment]
> @bestRunner Taiwan. By the way, could you please provide the page that you want to crawl? Thank!
好的，謝謝，請問封IP嚴重嗎

**Comment by bestRunner** [comment]
> @bestRunner Taiwan. By the way, could you please provide the page that you want to crawl? Thank!

主頁還是公共Page，例如：“https://www.facebook.com/CNBMNigeria/”，請問您有wechat或其他的聯係方式嗎？有的話方便加一下好友嗎
