### ISSUE TITLE
Traceback: edge_list might be empty

### ISSUE THREAD

**Issue by moon71117** [TLYu0419/facebook_crawler#16]
Hello! Thank you for developing and maintaining this useful package!
I had a problem recently when backing up this facebook page: https://www.facebook.com/111182238148502
In the process of crawling, "Break Times" keep showing up every few seconds and requesting the same post repeatedly.
I found it might have something to do with an empty edge_list. I have no idea how to fix that now.

<img width="2047" alt="Screen Shot 2022-05-26 at 15 43 53" src="https://user-images.githubusercontent.com/32948991/170442527-71e1e8f5-dea2-45e1-999d-cbd3d9c2bb1f.png">

It would be wonderful if you could kindly fix that in the next update. Thank you!

**Comment by andyfcx** [comment]
Hi @moon71117, your issue may come from these lines:
https://github.com/TLYu0419/facebook_crawler/blob/main/facebook_crawler.py#L67-L92
