### ISSUE TITLE
Can not crawl on AWS server

### ISSUE THREAD

**Issue by mnliv** [TLYu0419/facebook_crawler#19]
Hi team,
I have crawled successfully on local machine. However, when using it on AWS EC2, an error like this occurs.
Please check your target fanpages has up to date.
If so, you can ignore this break time message, if not, please change your Internet IP and retun this crawler.
Many thanks!
![MicrosoftTeams-image](https://user-images.githubusercontent.com/62173397/174261342-0a7850a7-058c-4812-84c8-0439388e14e4.png)

**Comment by TLYu0419** [comment]
Hi Mnliv,
Please utilize this package on your local machine. Thanks!
