### ISSUE TITLE
提示如下错误

### ISSUE THREAD

**Issue by arthasking123** [TLYu0419/facebook_crawler#5]
![image](https://user-images.githubusercontent.com/16257131/124212212-253b9e80-db21-11eb-88b3-de6e2dc102a4.png)

**Comment by TLYu0419** [comment]
Could you please provide the fans page link you try to collect?

**Comment by arthasking123** [comment]
https://www.facebook.com/diudiu333

**Comment by TLYu0419** [comment]
It works well now, but I don't know what happened. Would you please try it again? Thanks!
