### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by May81273** [TLYu0419/facebook_crawler#6]
I got the same problem"IndexError: list index out of range".
pageurl is"https://www.facebook.com/josepereiracoutinho.macau"
The resp of this url is different from other url, There is no page_id in resp so when "pageid = re.findall('page_id=(.*?)"',resp.text)[0]" runs, page_id try to get list[0[ from a empty list.
Could you solve this qusetion?
Thanks,

**Comment by May81273** [comment]
![image](https://user-images.githubusercontent.com/86956044/124454131-b4171800-ddba-11eb-839f-e662edf9a4ec.png)
But in elements of website, I can find page_id.
I don't know why there is no page_id in resp.text.

**Comment by May81273** [comment]
![image](https://user-images.githubusercontent.com/86956044/124455214-e2492780-ddbb-11eb-925f-4048aac6f395.png)
I use this page_id, then I get result sucessfully.

**Comment by TLYu0419** [comment]
Hi @May81273,
It's good to hear you had solved this problem. 
If you like this project, please give me support. Either donate, star or share are good for me, tks!
